use_frameworks!

platform :ios, '9.0'

target 'BorderButton_Example' do
  pod 'BorderButton', :path => '../'

  target 'BorderButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
